version: "3.9"

services:
  api:
    build: .
    container_name: taskforge_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: taskforge_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskforge
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: taskforge_redis
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A backend.tasks worker --loglevel=info
    depends_on:
      - redis

